name: Lint Validation

on:
  pull_request:
    branches:
      - staging

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Run Lint
        run: npm run lint